[tool.bumpversion]
current_version = "3.0.0"

[[tool.bumpversion.files]]
filename = "src/glassesValidator/version.py"


[[tool.bumpversion.files]]
filename = "README.md"
search = "GlassesValidator v{current_version}"
replace = "GlassesValidator v{new_version}"